#!/usr/bin/env python3
"""
Generate fixed-order alpha_s variations of an expensive N3LO (a_s^3) prediction, in
the NNLOjet text format, so they can be consumed by make_theory_corr.py exactly like
a real NNLOjet run.

Construction (order-by-order expansion; Z+jet born at a_s):

    FO(N3LO, a_s) = FO(NNLO, a_s)            # through a_s^2, at the a_s PDF (DYTurbo member)
                  + (a_s/a_s0)^3 * a_s^3-only(a_s0)   # top coefficient, rescaled from the nominal

Only the highest (a_s^3) coefficient is extrapolated; it is available for the nominal
PDF only (the expensive run).  The a_s^1+a_s^2 base is taken directly at each a_s from
the DYTurbo through-a_s^2 member files (full/correlated PDF+a_s), matching the input
already used for the lower-order DYTurbo alpha_s variations.
"""

import argparse
import glob
import os
import re

import numpy as np


def num(x):
    return float(x.replace("p", "."))


def ybin_suffixes(nnlo_only_prefix):
    """List of (suffix_str, ylo, yhi) from the a_s^3 (nnlo_only) per-y-bin files."""
    out = []
    for fn in sorted(glob.glob(f"{nnlo_only_prefix}__*.dat")):
        m = re.search(r"__(-?[\dp.]+)__(-?[\dp.]+)\.dat$", fn)
        lo, hi = m.group(1), m.group(2)
        out.append((f"{lo}__{hi}", num(lo), num(hi)))
    return out


def read_nnlojet_ybin_central(path):
    """{k(int qT low edge): (value, err)} for the central scale (cols 3,4), 1-GeV qT."""
    d = {}
    for line in open(path):
        if line.startswith("#") or not line.strip():
            continue
        c = line.split()
        if len(c) < 5:
            continue
        d[int(float(c[0]))] = (float(c[3]), float(c[4]))
    return d


def read_dyturbo_ybin(path, ylo, yhi, qlo=60.0, qhi=120.0):
    """DYTurbo through-a^2 base: integrated (value, unc) per qT bin, rebinned to the
    NNLOjet Y bin [ylo, yhi] at Q in [qlo, qhi].  The DYTurbo Y grid (0.1-wide in
    |Y| in [1,2.5]) does NOT nest into the 0.25-wide NNLOjet y-bins, so we take the
    *fractional overlap* of each DYTurbo Y bin with [ylo, yhi] (flat within the bin).
    Returns sorted [(qtlo, qthi, val, unc)]."""
    rows = [l.split() for l in open(path) if not l.startswith("#") and l.strip()]
    d = np.array([[float(x) for x in r] for r in rows])
    sel = (
        (d[:, 0] == qlo)
        & (d[:, 1] == qhi)
        & ~((d[:, 4] == 0.0) & (d[:, 5] == 100.0))  # drop inclusive qT bin
        & ~((d[:, 2] == -5.0) & (d[:, 3] == 5.0))  # drop inclusive Y bin
    )
    d = d[sel]
    acc = {}
    for dylo, dyhi, qtlo, qthi, val, unc in zip(
        d[:, 2], d[:, 3], d[:, 4], d[:, 5], d[:, 6], d[:, 7]
    ):
        overlap = min(dyhi, yhi) - max(dylo, ylo)
        if overlap <= 1e-9:
            continue
        frac = overlap / (dyhi - dylo)
        key = (round(qtlo, 3), round(qthi, 3))
        v, u2 = acc.get(key, (0.0, 0.0))
        acc[key] = (v + frac * val, u2 + (frac * unc) ** 2)
    return sorted([(a, b, v, np.sqrt(u2)) for (a, b), (v, u2) in acc.items()])


def combine(dybins, a3, rescale, qmin):
    """N3LO = base + rescale * a^3, on a common qT grid: sub-1-GeV DYTurbo bins merged to
    1-GeV integers (a^3 native), >=1-GeV DYTurbo bins kept (a^3 summed into them).
    Returns sorted [(qtlo, qthi, value, err)] for qT >= qmin where a^3 is available."""
    out = []
    # sub-1-GeV DYTurbo bins -> integer 1-GeV bins
    acc = {}
    for a, b, val, unc in dybins:
        if b - a < 1.0 - 1e-6:
            k = int(a + 1e-9)
            e = acc.setdefault(k, [0.0, 0.0, 0.0])
            e[0] += val
            e[1] += unc**2
            e[2] += b - a
    for k, (v, u2, w) in sorted(acc.items()):
        if abs(w - 1.0) > 1e-6 or k < qmin or k not in a3:
            continue
        a3v, a3e = a3[k]
        out.append(
            (
                float(k),
                float(k + 1),
                v + rescale * a3v,
                np.hypot(np.sqrt(u2), rescale * a3e),
            )
        )
    # >=1-GeV DYTurbo bins kept as-is
    for a, b, val, unc in dybins:
        if b - a < 1.0 - 1e-6 or a < qmin - 1e-9:
            continue
        ks = [k for k in range(int(a + 1e-9), int(b + 1e-9)) if k in a3]
        if len(ks) != int(round(b - a)):
            continue
        a3v = sum(a3[k][0] for k in ks)
        a3e = np.sqrt(sum(a3[k][1] ** 2 for k in ks))
        out.append((a, b, val + rescale * a3v, np.hypot(unc, rescale * a3e)))
    out.sort()
    return out


def write_dat(path, bins, alphas, member):
    header = (
        f"#alpha_s variation (a_s={alphas}, member{member}) generated by "
        "make_alphaS_variation_nnlojet.py -- central scale only\n"
        "#labels: ptz_lower[1] ptz_center[2] ptz_upper[3] tot_scale01[4] tot_scale01_Err[5]\n"
    )
    with open(path, "w") as f:
        f.write(header)
        for lo, hi, val, err in bins:
            f.write(f"{lo:.11E} {(lo + hi) / 2:.11E} {hi:.11E} {val:.11E} {err:.11E}\n")


def parse_members(specs):
    """['3:0.116', '6:0.120'] -> [(3, 0.116), (6, 0.120)]."""
    out = []
    for s in specs:
        m, a = s.split(":")
        out.append((int(m), float(a)))
    return out


def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "-a",
        "--nnloOnly",
        required=True,
        help="NNLOjet a_s^3-only (nnlo_only) refname, e.g. "
        "'/scratch/.../result/final/nnlo_only.ptz' "
        "(reads '<refname>__<ylo>__<yhi>.dat').",
    )
    p.add_argument(
        "-b",
        "--base",
        required=True,
        help="DYTurbo through-a^2 base file template with an '{i}' member "
        "placeholder, e.g. '.../MSHT20an3lo_as_smallrange/z0/"
        "results_z-2d-nnlo-vj-MSHT20an3lo_as_smallrange-member{i}-scetlibmatch.txt'.",
    )
    p.add_argument(
        "-m",
        "--members",
        required=True,
        nargs="+",
        help="Members to produce as 'index:alphaS', e.g. 3:0.116 6:0.120 "
        "(index matches the PDF alpha_s set / SCETlib pdf{N}).",
    )
    p.add_argument(
        "--alphas0",
        type=float,
        default=0.118,
        help="Reference alpha_s of the expensive a_s^3 run (default 0.118).",
    )
    p.add_argument(
        "-o",
        "--out",
        required=True,
        help="Output refname template with '{i}', e.g. "
        "'.../n3lo_asvar_member{i}.ptz' (writes '<...>__<ylo>__<yhi>.dat').",
    )
    p.add_argument(
        "--qmin",
        type=float,
        default=5.0,
        help="Lowest qT bin to emit (default 5; where the a^3 run exists).",
    )
    return p.parse_args()


def main():
    args = parse_args()
    members = parse_members(args.members)
    suffixes = ybin_suffixes(args.nnloOnly)
    if not suffixes:
        raise SystemExit(f"No nnlo_only files found at '{args.nnloOnly}__*.dat'")
    print(f"y-bins: {len(suffixes)} | members: {members} | qmin: {args.qmin}")

    for member, alphas in members:
        rescale = (alphas / args.alphas0) ** 3
        base_file = args.base.format(i=member)
        if not os.path.isfile(base_file):
            raise SystemExit(f"Missing DYTurbo base for member {member}: {base_file}")
        out_ref = args.out.format(i=member)
        os.makedirs(os.path.dirname(out_ref) or ".", exist_ok=True)
        nbins_written = 0
        for suffix, ylo, yhi in suffixes:
            a3 = read_nnlojet_ybin_central(f"{args.nnloOnly}__{suffix}.dat")
            dybins = read_dyturbo_ybin(base_file, ylo, yhi)
            bins = combine(dybins, a3, rescale, args.qmin)
            if bins:
                write_dat(f"{out_ref}__{suffix}.dat", bins, alphas, member)
                nbins_written += 1
        tag = " [central/reference]" if abs(alphas - args.alphas0) < 1e-9 else ""
        print(
            f"  member{member} (a_s={alphas}, (a_s/a_s0)^3={rescale:.5f}){tag}: "
            f"wrote {nbins_written} y-bin files -> {out_ref}__*.dat"
        )


if __name__ == "__main__":
    main()
